// @ts-nocheck
import { useEffect, useState, useRef } from 'react'
import { useRouter } from 'next/router'
import { supabase } from '../../src/lib/supabase'
import {
  checkJobSeekerAuth, calculateProfileStrength, compressImage,
  validateFileSize, saveUserLocation,
  getNightModePreference, setNightModePreference,
} from '../../src/lib/jobseeker-utils'
import JobSeekerSidebar from '../../src/components/JobSeekerSidebar'

// ══════════════════════════════════════════════════════════
// JOB SEEKER PROFILE v3.1
// Fixes: no size limit (compress all), centered error modal,
// motivational messages, share/refer, photo everywhere,
// auto CV text + PDF download
// ══════════════════════════════════════════════════════════

const CITIES = ['Delhi','Mumbai','Bangalore','Hyderabad','Pune','Chennai','Noida','Gurgaon','Kolkata','Ahmedabad','Jaipur','Lucknow','Chandigarh','Kochi','Nagpur','Indore','Bhopal','Surat','Vadodara','Patna','Ranchi','Coimbatore','Visakhapatnam','Bhubaneswar','Other']
const QUALIFICATIONS = ['B.Tech/B.E.','M.Tech/M.E.','MCA','BCA','MBA/PGDM','B.Sc','M.Sc','BBA','B.Com','M.Com','BA','MA','MBBS','BDS','B.Pharm','M.Pharm','CA','CS','CMA/ICWA','LLB','LLM','PhD','Diploma','ITI','12th Pass','10th Pass','Other']
const NOTICE_PERIODS = ['Immediate','7 days','15 days','1 month','2 months','3 months']
const WORK_MODES = ['WFH','WFO','Hybrid']
const JOB_TYPES = ['Full Time','Part Time']
const EMP_TYPES = ['Permanent','Temporary','Contractual']
const VIBE_MODES = [
  { value: 'fun', label: '🎮 Fun & Social' },
  { value: 'professional', label: '💼 Professional' },
  { value: 'focus', label: '🎯 Quick Apply' },
]

// 20 motivational profile completion messages
const MOTIVATION = [
  "🚀 Profiles with photos get 3x more recruiter views!",
  "💡 Add your skills — recruiters search by skills first.",
  "📈 Complete profiles rank higher in search results.",
  "🎯 Add your expected CTC to get relevant offers only.",
  "⚡ Recruiters spend avg 6 seconds on a profile — make it count!",
  "🔥 Candidates with LinkedIn get 2x more direct messages.",
  "🌟 Your notice period matters — keep it updated always.",
  "📱 Add your mobile number so recruiters can reach you instantly.",
  "🎓 Add your qualification — it filters into top searches.",
  "💼 Your current role tells recruiters what you can do now.",
  "🏆 Top 10% profiles have all fields filled — are you there yet?",
  "📍 Add your city — location-based jobs match better.",
  "🤝 Profiles with work mode preference get faster responses.",
  "📄 Download your auto-generated CV — share it anywhere!",
  "🔔 Recruiters shortlist faster when they see your college name.",
  "💰 Profiles with CTC details skip the salary negotiation stage.",
  "🌐 Add your GitHub/Portfolio — it sets you apart instantly.",
  "🎯 Employment type preference helps match contract/permanent jobs.",
  "⭐ Keep your profile fresh — update every 30 days for better reach.",
  "📧 Verified email = priority placement in recruiter inboxes.",
]

function multiToggle(current, val) {
  const arr = current ? current.split(',').map(s => s.trim()).filter(Boolean) : []
  const idx = arr.indexOf(val)
  if (idx === -1) arr.push(val)
  else arr.splice(idx, 1)
  return arr.join(', ')
}
function hasVal(current, val) {
  return (current || '').split(',').map(s => s.trim()).includes(val)
}

// Generate plain-text CV for download
function generateCV(user, form) {
  const line = (label, val) => val ? `${label}: ${val}\n` : ''
  return `
╔══════════════════════════════════════════╗
   CURRICULUM VITAE
╚══════════════════════════════════════════╝

${(user?.full_name || '').toUpperCase()}
${line('Email', user?.email)}${line('Mobile', form.mobile)}${line('City', form.city)}${line('LinkedIn', form.linkedin)}${line('GitHub/Portfolio', form.github)}

── PROFESSIONAL SUMMARY ──────────────────
${line('Current Role', form.role)}${line('Total Experience', form.experience ? form.experience + ' years' : '')}${line('Notice Period', form.notice_period)}${line('Current CTC', form.current_ctc ? '₹' + form.current_ctc + ' LPA' : '')}${line('Expected CTC', form.expected_ctc ? '₹' + form.expected_ctc + ' LPA' : '')}${line('Work Mode', form.work_mode)}${line('Job Type', form.job_type)}${line('Employment Type', form.employment_type)}
── EDUCATION ─────────────────────────────
${line('Qualification', form.qualification)}${line('Branch / Specialization', form.branch)}${line('College / University', form.college)}${line('Graduation Year', form.graduation_year)}
── SKILLS ────────────────────────────────
${form.skills || 'Not added'}

──────────────────────────────────────────
Generated by RecruitBase Pro | ${new Date().toLocaleDateString('en-IN')}
`.trim()
}

export default function JobSeekerProfile() {
  const router = useRouter()
  const [user, setUser] = useState(null)
  const [form, setForm] = useState({})
  const [profileId, setProfileId] = useState(null)
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [profileStrength, setProfileStrength] = useState({ score: 0, missing: [] })
  const [uploading, setUploading] = useState(false)
  const [toast, setToast] = useState(null)
  const [modal, setModal] = useState(null) // { title, msg, type }
  const [nightMode, setNightMode] = useState(false)
  const [vibeMode, setVibeMode] = useState('fun')
  const [locSaved, setLocSaved] = useState(false)
  const [locLoading, setLocLoading] = useState(false)
  const [userSettings, setUserSettings] = useState({ segment: 'fresher', vibe: 'fun' })
  const [motiveTip] = useState(() => MOTIVATION[Math.floor(Math.random() * MOTIVATION.length)])
  const [showShare, setShowShare] = useState(false)
  const photoRef = useRef(null)

  function showToast(msg, type = 'success') {
    setToast({ msg, type })
    setTimeout(() => setToast(null), 3500)
  }
  function showModal(title, msg, type = 'error') {
    setModal({ title, msg, type })
  }

  function sf(k, v) {
    const updated = { ...form, [k]: v }
    setForm(updated)
    setProfileStrength(calculateProfileStrength(updated))
  }

  useEffect(() => { setNightMode(getNightModePreference()) }, [])

  useEffect(() => {
    let cancelled = false
    async function init() {
      try {
        const { user: au, redirect } = await checkJobSeekerAuth()
        if (cancelled) return
        if (redirect) { router.push(redirect); return }
        if (!au) return
        setUser(au)
        setVibeMode(au.vibe_mode || 'fun')
        setUserSettings({ segment: au.experience_segment || 'fresher', vibe: au.vibe_mode || 'fun' })
        setLocSaved(!!au.latitude)

        const { data: profile } = await supabase
          .from('profiles').select('*').eq('created_by', au.id)
          .order('created_at', { ascending: true }).limit(1).single()

        if (cancelled) return
        if (profile) {
          setProfileId(profile.id)
          setForm({ ...profile, name: au.full_name || '', email: au.email || '', mobile: au.mobile || profile.mobile || '' })
          setProfileStrength(calculateProfileStrength({ ...profile, name: au.full_name, email: au.email }))
        } else {
          const init = { name: au.full_name || '', email: au.email || '', mobile: au.mobile || '' }
          setForm(init)
          setProfileStrength(calculateProfileStrength(init))
        }
        setLoading(false)
      } catch (e) {
        if (!cancelled) { setError('Something went wrong loading your profile.'); setLoading(false) }
      }
    }
    init()
    return () => { cancelled = true }
  }, [])

  async function saveProfile() {
    if (!form.mobile?.trim()) { showModal('Mobile Required', 'Please add your mobile number so recruiters can contact you.'); return }
    if (!user) return
    setSaving(true)

    const payload = {
      name: user.full_name || '',
      email: user.email || '',
      mobile: (form.mobile || '').replace(/\D/g, '').slice(0, 15),
      role: form.role || '',
      qualification: form.qualification || '',
      branch: form.branch || '',
      college: form.college || '',
      graduation_year: form.graduation_year || null,
      skills: form.skills || '',
      experience: form.experience ? parseFloat(String(form.experience)) : null,
      current_ctc: form.current_ctc ? parseFloat(String(form.current_ctc)) : null,
      expected_ctc: form.expected_ctc ? parseFloat(String(form.expected_ctc)) : null,
      notice_period: form.notice_period || '',
      work_mode: form.work_mode || '',
      job_type: form.job_type || '',
      employment_type: form.employment_type || '',
      city: form.city || '',
      linkedin: form.linkedin || '',
      github: form.github || '',
      photo_url: form.photo_url || user.photo_url || '',
      segment: (form.experience || 0) > 1 ? 'experienced' : 'fresher',
      status: 'New',
      source: 'Job Portal',
      created_by: user.id,
      type: 'Candidate',
    }

    let saveError
    if (profileId) {
      const res = await supabase.from('profiles').update(payload).eq('id', profileId)
      saveError = res.error
    } else {
      const { data: existing } = await supabase.from('profiles').select('id').eq('created_by', user.id).limit(1).single()
      if (existing) {
        setProfileId(existing.id)
        const res = await supabase.from('profiles').update(payload).eq('id', existing.id)
        saveError = res.error
      } else {
        const res = await supabase.from('profiles').insert(payload).select().single()
        saveError = res.error
        if (res.data) setProfileId(res.data.id)
      }
    }

    if (saveError) {
      showModal('Save Failed', 'Could not save your profile. Please check your internet connection and try again.')
    } else {
      setSaved(true)
      showToast('✅ Profile saved! Recruiters can now find you.')
      setTimeout(() => setSaved(false), 3000)
    }
    setSaving(false)
  }

  async function handlePhotoUpload(e) {
    const file = e.target.files?.[0]
    if (!file || !user) return
    // No size limit — we compress everything
    setUploading(true)
    try {
      // Compress all images regardless of size
      const blob = file.type.startsWith('image/') ? await compressImage(file, 250, 600) : file
      const ext = file.name.split('.').pop() || 'jpg'
      const path = `profiles/${user.id}/photo.${ext}`
      const { error: upErr } = await supabase.storage.from('uploads').upload(path, blob, { upsert: true, contentType: 'image/jpeg' })
      if (upErr) { showModal('Upload Failed', 'Could not upload photo. Please try a different image.'); setUploading(false); return }
      const { data: urlData } = supabase.storage.from('uploads').getPublicUrl(path)
      if (urlData?.publicUrl) {
        const photoUrl = urlData.publicUrl
        sf('photo_url', photoUrl)
        // ✅ Save to BOTH app_users AND profiles so it reflects everywhere
        await supabase.from('app_users').update({ photo_url: photoUrl }).eq('id', user.id)
        if (profileId) await supabase.from('profiles').update({ photo_url: photoUrl }).eq('id', profileId)
        setUser(u => ({ ...u, photo_url: photoUrl }))
        showToast('📸 Photo updated everywhere!')
      }
    } catch { showModal('Upload Error', 'File could not be processed. Please try a JPG or PNG image.') }
    setUploading(false)
  }

  async function detectLocation() {
    if (!user) return
    setLocLoading(true)
    const loc = await saveUserLocation(user.id)
    setLocLoading(false)
    if (loc) { setLocSaved(true); showToast(`📍 Location saved via ${loc.source === 'gps' ? 'GPS' : 'IP'}!`) }
    else showModal('Location Error', 'Could not detect location. Please allow location access in your browser settings.')
  }

  async function saveSettings() {
    if (!user) return
    await supabase.from('app_users').update({ experience_segment: userSettings.segment, vibe_mode: userSettings.vibe }).eq('id', user.id)
    setVibeMode(userSettings.vibe)
    showToast('Preferences saved!')
  }

  function downloadCV() {
    const text = generateCV(user, form)
    const blob = new Blob([text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${(user?.full_name || 'CV').replace(/\s+/g, '_')}_Resume.txt`
    a.click()
    URL.revokeObjectURL(url)
    showToast('📄 CV downloaded!')
  }

  function shareProfile() {
    const text = `Hey! I found this awesome job portal. Check out RecruitBase Pro — it connects candidates directly with top recruiters!\n\nhttps://smilingdbms.vercel.app/jobseeker`
    if (navigator.share) {
      navigator.share({ title: 'Join RecruitBase Pro', text, url: 'https://smilingdbms.vercel.app/jobseeker' }).catch(() => {})
    } else {
      navigator.clipboard?.writeText(text)
      showToast('🔗 Referral link copied!')
    }
    setShowShare(false)
  }
  function shareWhatsApp() {
    const text = encodeURIComponent(`Hey! Check out RecruitBase Pro — best platform to find jobs and connect with recruiters directly.\n👉 https://smilingdbms.vercel.app/jobseeker`)
    window.open(`https://wa.me/?text=${text}`, '_blank')
    setShowShare(false)
  }

  const theme = { bg: 'var(--bg)', bg2: 'var(--bg2)', bg3: 'var(--bg2)', tx: 'var(--tx)', muted: 'var(--mu)', bd: 'rgba(255,255,255,0.06)', accent: '#6c8cff' }
  const inp = { width: '100%', background: theme.bg3, border: `1px solid ${theme.bd}`, borderRadius: 10, padding: '10px 14px', color: theme.tx, fontSize: 14, fontFamily: 'inherit', outline: 'none', boxSizing: 'border-box' }
  const inpRO = { ...inp, opacity: 0.55, cursor: 'not-allowed', background: theme.bg2 }
  const lbl = { display: 'block', fontSize: 11, fontWeight: 600, color: theme.muted, textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 5, marginTop: 14 }
  const card = { background: 'rgba(255,255,255,0.02)', borderRadius: 14, border: `1px solid ${theme.bd}`, padding: 22, marginBottom: 16 }

  const chipBtn = (val, current, onToggle, color) => (
    <button key={val} onClick={() => onToggle(val)} style={{ padding: '7px 14px', borderRadius: 20, cursor: 'pointer', fontSize: 12, fontFamily: 'inherit', border: `1px solid ${hasVal(current, val) ? color : theme.bd}`, background: hasVal(current, val) ? `${color}18` : 'rgba(255,255,255,0.03)', color: hasVal(current, val) ? color : theme.muted, transition: 'all 0.15s', marginBottom: 6 }}>{val}</button>
  )

  const photoSrc = form.photo_url || user?.photo_url || null

  if (loading) return (
    <div style={{ minHeight: '100vh', background: theme.bg, display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'Outfit',sans-serif" }}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;800&display=swap')`}</style>
      <div style={{ textAlign: 'center', color: theme.muted }}>
        <div style={{ fontSize: 32, marginBottom: 12 }}>⏳</div>
        <div>Loading your profile...</div>
      </div>
    </div>
  )

  if (error) return (
    <div style={{ minHeight: '100vh', background: theme.bg, display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'Outfit',sans-serif" }}>
      <div style={{ textAlign: 'center', color: theme.tx, padding: 24 }}>
        <div style={{ fontSize: 48, marginBottom: 12 }}>⚠️</div>
        <div style={{ fontSize: 18, fontWeight: 600, marginBottom: 8 }}>{error}</div>
        <button onClick={() => window.location.reload()} style={{ background: theme.accent, color: '#fff', border: 'none', borderRadius: 10, padding: '10px 24px', cursor: 'pointer', fontFamily: 'inherit', fontWeight: 600 }}>Refresh Page</button>
      </div>
    </div>
  )

  return (
    <div style={{ minHeight: '100vh', background: theme.bg, color: theme.tx, fontFamily: "'Outfit',sans-serif" }}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Outfit:wght@400;500;600;700;800&display=swap');*{box-sizing:border-box;margin:0;padding:0}input:focus,select:focus,textarea:focus{border-color:${theme.accent}!important}select option{background:${theme.bg3}}`}</style>

      {/* ── Toast (corner) ── */}
      {toast && (
        <div style={{ position: 'fixed', top: 16, right: 16, zIndex: 9999, background: toast.type === 'success' ? '#0d2a1a' : '#2a0d0d', border: `1px solid ${toast.type === 'success' ? '#3dd68c55' : '#ff505055'}`, color: toast.type === 'success' ? '#3dd68c' : '#ff5050', padding: '12px 20px', borderRadius: 12, fontSize: 13, fontWeight: 600, maxWidth: 320, boxShadow: '0 4px 20px rgba(0,0,0,0.5)' }}>
          {toast.msg}
        </div>
      )}

      {/* ── Centered Error Modal ── */}
      {modal && (
        <div style={{ position: 'fixed', inset: 0, zIndex: 10000, background: 'rgba(0,0,0,0.7)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20 }}>
          <div style={{ background: theme.bg2, border: `1px solid ${modal.type === 'error' ? '#ff505044' : '#3dd68c44'}`, borderRadius: 16, padding: 28, maxWidth: 400, width: '100%', boxShadow: '0 8px 40px rgba(0,0,0,0.6)' }}>
            <div style={{ fontSize: 36, textAlign: 'center', marginBottom: 12 }}>{modal.type === 'error' ? '⚠️' : '✅'}</div>
            <div style={{ fontSize: 16, fontWeight: 700, textAlign: 'center', marginBottom: 8 }}>{modal.title}</div>
            <div style={{ fontSize: 13, color: theme.muted, textAlign: 'center', lineHeight: 1.6, marginBottom: 20 }}>{modal.msg}</div>
            <button onClick={() => setModal(null)} style={{ width: '100%', padding: '11px', borderRadius: 10, background: modal.type === 'error' ? 'rgba(255,80,80,0.15)' : 'rgba(61,214,140,0.15)', color: modal.type === 'error' ? '#ff5050' : '#3dd68c', border: `1px solid ${modal.type === 'error' ? '#ff505044' : '#3dd68c44'}`, cursor: 'pointer', fontFamily: 'inherit', fontWeight: 600, fontSize: 14 }}>
              Close
            </button>
          </div>
        </div>
      )}

      {/* ── Share Modal ── */}
      {showShare && (
        <div style={{ position: 'fixed', inset: 0, zIndex: 10000, background: 'rgba(0,0,0,0.7)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20 }}>
          <div style={{ background: theme.bg2, border: `1px solid ${theme.bd}`, borderRadius: 16, padding: 28, maxWidth: 380, width: '100%' }}>
            <div style={{ fontSize: 24, textAlign: 'center', marginBottom: 8 }}>🎉 Refer a Friend</div>
            <div style={{ fontSize: 13, color: theme.muted, textAlign: 'center', marginBottom: 20 }}>Share RecruitBase Pro with friends looking for jobs!</div>
            <button onClick={shareWhatsApp} style={{ width: '100%', padding: 12, borderRadius: 10, background: 'rgba(37,211,102,0.12)', color: '#25D366', border: '1px solid rgba(37,211,102,0.3)', cursor: 'pointer', fontFamily: 'inherit', fontWeight: 600, fontSize: 14, marginBottom: 10 }}>
              📱 Share on WhatsApp
            </button>
            <button onClick={shareProfile} style={{ width: '100%', padding: 12, borderRadius: 10, background: `${theme.accent}18`, color: theme.accent, border: `1px solid ${theme.accent}33`, cursor: 'pointer', fontFamily: 'inherit', fontWeight: 600, fontSize: 14, marginBottom: 10 }}>
              🔗 Copy Referral Link
            </button>
            <button onClick={() => setShowShare(false)} style={{ width: '100%', padding: 10, borderRadius: 10, background: 'transparent', color: theme.muted, border: `1px solid ${theme.bd}`, cursor: 'pointer', fontFamily: 'inherit', fontSize: 13 }}>
              Cancel
            </button>
          </div>
        </div>
      )}

      {/* SIDEBAR */}
      <JobSeekerSidebar
        userName={user?.full_name || ''}
        photoUrl={photoSrc}
        xp={user?.xp_points || 0}
        streak={user?.streak_count || 0}
        vibeMode={vibeMode}
        onVibeChange={(v) => { setVibeMode(v); if (user) supabase.from('app_users').update({ vibe_mode: v }).eq('id', user.id) }}
        nightMode={nightMode}
        onNightModeChange={(v) => { setNightMode(v); setNightModePreference(v) }}
      />

      <div style={{ padding: '16px 20px', maxWidth: 700, margin: '0 auto' }}>

        {/* Header */}
        <div style={{ marginBottom: 20, display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 10 }}>
          <div>
            <div style={{ fontSize: 22, fontWeight: 800 }}>My Profile</div>
            <div style={{ color: theme.muted, fontSize: 13, marginTop: 4 }}>Keep it updated — recruiters find you through this data</div>
          </div>
          <div style={{ display: 'flex', gap: 8 }}>
            <button onClick={downloadCV} style={{ padding: '8px 14px', borderRadius: 10, background: 'rgba(16,185,129,0.12)', color: '#10B981', border: '1px solid rgba(16,185,129,0.3)', cursor: 'pointer', fontFamily: 'inherit', fontWeight: 600, fontSize: 12 }}>
              📄 Download CV
            </button>
            <button onClick={() => setShowShare(true)} style={{ padding: '8px 14px', borderRadius: 10, background: 'rgba(245,158,11,0.12)', color: '#F59E0B', border: '1px solid rgba(245,158,11,0.3)', cursor: 'pointer', fontFamily: 'inherit', fontWeight: 600, fontSize: 12 }}>
              🎉 Refer Friend
            </button>
          </div>
        </div>

        {/* Motivational tip */}
        <div style={{ background: 'rgba(108,140,255,0.06)', border: `1px solid ${theme.accent}22`, borderRadius: 12, padding: '10px 16px', marginBottom: 16, fontSize: 12, color: '#9aabff', lineHeight: 1.5 }}>
          {motiveTip}
        </div>

        {/* Profile Strength */}
        <div style={{ ...card, borderLeft: `3px solid ${profileStrength.score >= 80 ? '#3dd68c' : profileStrength.score >= 50 ? '#ffd60a' : '#ff6b6b'}` }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
            <span style={{ fontSize: 15, fontWeight: 700 }}>Profile Strength</span>
            <span style={{ fontSize: 22, fontWeight: 800, color: profileStrength.score >= 80 ? '#3dd68c' : profileStrength.score >= 50 ? '#ffd60a' : '#ff6b6b' }}>{profileStrength.score}%</span>
          </div>
          <div style={{ height: 8, background: 'rgba(255,255,255,0.06)', borderRadius: 4, overflow: 'hidden', marginBottom: 8 }}>
            <div style={{ height: '100%', width: `${profileStrength.score}%`, background: profileStrength.score >= 80 ? '#3dd68c' : profileStrength.score >= 50 ? '#ffd60a' : '#ff6b6b', borderRadius: 4, transition: 'width 0.5s' }} />
          </div>
          {profileStrength.score >= 80
            ? <div style={{ fontSize: 12, color: '#3dd68c' }}>🎉 Great profile! 1-tap apply is unlocked.</div>
            : <div style={{ fontSize: 12, color: '#ffd60a' }}>Add: <b>{profileStrength.missing.slice(0, 3).join(', ')}</b> to improve visibility.</div>
          }
        </div>

        {/* Photo Upload */}
        <div style={card}>
          <div style={{ fontSize: 14, fontWeight: 700, marginBottom: 12 }}>Profile Photo</div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
            <div style={{ width: 72, height: 72, borderRadius: 18, background: `${theme.accent}18`, display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden', border: `2px solid ${theme.accent}33`, flexShrink: 0 }}>
              {photoSrc
                ? <img src={photoSrc} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                : <span style={{ fontSize: 28, color: theme.accent, fontWeight: 700 }}>{(user?.full_name || '?')[0].toUpperCase()}</span>
              }
            </div>
            <div>
              <input ref={photoRef} type="file" accept="image/*" onChange={handlePhotoUpload} style={{ display: 'none' }} disabled={uploading} />
              <button onClick={() => photoRef.current?.click()} disabled={uploading} style={{ background: `${theme.accent}18`, color: theme.accent, border: `1px solid ${theme.accent}33`, borderRadius: 10, padding: '9px 18px', fontSize: 13, fontWeight: 600, cursor: 'pointer', fontFamily: 'inherit', opacity: uploading ? 0.5 : 1 }}>
                {uploading ? 'Uploading...' : '📸 Upload Photo'}
              </button>
              <div style={{ fontSize: 11, color: theme.muted, marginTop: 5 }}>Any size · Auto-compressed · JPG/PNG · Reflects everywhere</div>
            </div>
          </div>
        </div>

        {/* Personal Info */}
        <div style={card}>
          <div style={{ fontSize: 14, fontWeight: 700 }}>Personal Information</div>
          <label style={lbl}>Full Name <span style={{ color: '#ffd60a', fontSize: 10 }}>(from your account · contact support to change)</span></label>
          <input style={inpRO} value={user?.full_name || ''} readOnly />
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
            <div>
              <label style={lbl}>Email <span style={{ color: '#ffd60a', fontSize: 10 }}>(locked)</span></label>
              <input style={inpRO} value={user?.email || ''} readOnly />
            </div>
            <div>
              <label style={lbl}>Mobile *</label>
              <input style={inp} value={form.mobile || ''} onChange={e => sf('mobile', e.target.value.replace(/\D/g, '').slice(0, 10))} placeholder="10-digit number" />
            </div>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
            <div>
              <label style={lbl}>City</label>
              <select style={inp} value={form.city || ''} onChange={e => sf('city', e.target.value)}>
                <option value="">Select City</option>
                {CITIES.map(c => <option key={c}>{c}</option>)}
              </select>
            </div>
            <div>
              <label style={lbl}>LinkedIn URL</label>
              <input style={inp} value={form.linkedin || ''} onChange={e => sf('linkedin', e.target.value)} placeholder="linkedin.com/in/..." />
            </div>
          </div>
          <label style={lbl}>GitHub / Portfolio URL</label>
          <input style={inp} value={form.github || ''} onChange={e => sf('github', e.target.value)} placeholder="github.com/username or portfolio link" />
          <div style={{ marginTop: 14, display: 'flex', alignItems: 'center', gap: 10 }}>
            <button onClick={detectLocation} disabled={locLoading} style={{ background: 'rgba(108,140,255,0.08)', color: theme.accent, border: `1px solid rgba(108,140,255,0.2)`, borderRadius: 10, padding: '8px 14px', fontSize: 12, cursor: 'pointer', fontFamily: 'inherit', opacity: locLoading ? 0.5 : 1 }}>
              {locLoading ? 'Detecting...' : '📍 Detect My Location'}
            </button>
            {locSaved && <span style={{ fontSize: 11, color: '#3dd68c' }}>Location saved ✓</span>}
          </div>
        </div>

        {/* Professional Details */}
        <div style={card}>
          <div style={{ fontSize: 14, fontWeight: 700 }}>Professional Details</div>
          <label style={lbl}>Current Role / Designation</label>
          <input style={inp} value={form.role || ''} onChange={e => sf('role', e.target.value)} placeholder="e.g. Software Engineer, HR Manager, Student" />
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
            <div>
              <label style={lbl}>Total Experience (years)</label>
              <input style={inp} type="number" step="0.5" min="0" max="50" value={form.experience || ''} onChange={e => sf('experience', e.target.value ? parseFloat(e.target.value) : null)} placeholder="0 = Fresher" />
            </div>
            <div>
              <label style={lbl}>Notice Period</label>
              <select style={inp} value={form.notice_period || ''} onChange={e => sf('notice_period', e.target.value)}>
                <option value="">Select</option>
                {NOTICE_PERIODS.map(n => <option key={n}>{n}</option>)}
              </select>
            </div>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
            <div>
              <label style={lbl}>Current CTC (₹ LPA)</label>
              <input style={inp} type="number" step="0.5" min="0" value={form.current_ctc || ''} onChange={e => sf('current_ctc', e.target.value ? parseFloat(e.target.value) : null)} placeholder="e.g. 8.5" />
            </div>
            <div>
              <label style={lbl}>Expected CTC (₹ LPA)</label>
              <input style={inp} type="number" step="0.5" min="0" value={form.expected_ctc || ''} onChange={e => sf('expected_ctc', e.target.value ? parseFloat(e.target.value) : null)} placeholder="e.g. 12" />
            </div>
          </div>
          <label style={lbl}>Work Mode (select all that apply)</label>
          <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
            {WORK_MODES.map(w => chipBtn(w, form.work_mode || '', (v) => sf('work_mode', multiToggle(form.work_mode || '', v)), '#6c8cff'))}
          </div>
          <label style={lbl}>Job Type</label>
          <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
            {JOB_TYPES.map(j => chipBtn(j, form.job_type || '', (v) => sf('job_type', multiToggle(form.job_type || '', v)), '#10B981'))}
          </div>
          <label style={lbl}>Employment Type</label>
          <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
            {EMP_TYPES.map(e => chipBtn(e, form.employment_type || '', (v) => sf('employment_type', multiToggle(form.employment_type || '', v)), '#F59E0B'))}
          </div>
        </div>

        {/* Education */}
        <div style={card}>
          <div style={{ fontSize: 14, fontWeight: 700 }}>Education</div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
            <div>
              <label style={lbl}>Highest Qualification</label>
              <select style={inp} value={form.qualification || ''} onChange={e => sf('qualification', e.target.value)}>
                <option value="">Select</option>
                {QUALIFICATIONS.map(q => <option key={q}>{q}</option>)}
              </select>
            </div>
            <div>
              <label style={lbl}>Branch / Specialization</label>
              <input style={inp} value={form.branch || ''} onChange={e => sf('branch', e.target.value)} placeholder="e.g. CSE, Finance, Marketing" />
            </div>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
            <div>
              <label style={lbl}>College / University</label>
              <input style={inp} value={form.college || ''} onChange={e => sf('college', e.target.value)} placeholder="College name" />
            </div>
            <div>
              <label style={lbl}>Graduation Year</label>
              <select style={inp} value={form.graduation_year || ''} onChange={e => sf('graduation_year', e.target.value)}>
                <option value="">Select Year</option>
                {Array.from({ length: 30 }, (_, i) => 2026 - i).map(y => <option key={y}>{y}</option>)}
              </select>
            </div>
          </div>
        </div>

        {/* Skills */}
        <div style={card}>
          <div style={{ fontSize: 14, fontWeight: 700 }}>Skills</div>
          <div style={{ fontSize: 12, color: theme.muted, marginTop: 4, marginBottom: 8 }}>Comma-separated · Recruiters search by skills first</div>
          <textarea rows={3} style={{ ...inp, resize: 'none' }} value={form.skills || ''} onChange={e => sf('skills', e.target.value)} placeholder="e.g. React, Node.js, Python, Leadership, Sales, Excel, Tally..." />
        </div>

        {/* Feed Preferences */}
        <div style={card}>
          <div style={{ fontSize: 14, fontWeight: 700, marginBottom: 12 }}>Feed Style Preference</div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
            <div>
              <label style={lbl}>Feed Style</label>
              <select style={inp} value={userSettings.vibe} onChange={e => setUserSettings(p => ({ ...p, vibe: e.target.value }))}>
                {VIBE_MODES.map(v => <option key={v.value} value={v.value}>{v.label}</option>)}
              </select>
            </div>
            <div style={{ display: 'flex', alignItems: 'flex-end' }}>
              <button onClick={saveSettings} style={{ width: '100%', padding: '10px', borderRadius: 10, fontSize: 13, fontWeight: 600, background: `${theme.accent}18`, color: theme.accent, border: `1px solid ${theme.accent}33`, cursor: 'pointer', fontFamily: 'inherit' }}>
                Save Preferences
              </button>
            </div>
          </div>
        </div>

        {/* Save Button */}
        <button onClick={saveProfile} disabled={saving} style={{ width: '100%', padding: 16, borderRadius: 14, fontSize: 16, fontWeight: 700, fontFamily: 'inherit', background: saved ? '#3dd68c' : theme.accent, color: '#fff', border: 'none', cursor: 'pointer', opacity: saving ? 0.6 : 1, transition: 'all 0.2s', marginBottom: 32 }}>
          {saving ? 'Saving...' : saved ? '✅ Profile Saved!' : '💾 Save Profile'}
        </button>

      </div>
    </div>
  )
}
